feat: create InsertEvent task for Google Calendar
kestra-io/plugin-googleworkspace pull request #158
Opened 2024-11-05 13:16 UTC by shrutimantri

2024-11-05 13:32 UTC, loicmathieu requested changes
Two remarks:
- AbstractInsertEvent is not necessary, you could merge it with InsertEvent (not mandatory)
- We have a new plugin property framework that is more capable that the current mechanism, you can see for ex how it works in this PR: https://github.com/kestra-io/plugin-redis/pull/73. Please use it for your future PR.

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +    @PluginProperty(dynamic = true)
```suggestion
    @PluginProperty
```

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +    @PluginProperty(dynamic = true)
```suggestion
    @PluginProperty
```

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +    @PluginProperty(dynamic = true)
```suggestion
    @PluginProperty
```

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +    @PluginProperty(dynamic = true)
```suggestion
    @PluginProperty
```

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +        EventDateTime eventStartTime = new EventDateTime().setDateTime(new DateTime(startTime.dateTime)).setTimeZone(startTime.timeZone);
You forget to render it

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +        EventDateTime eventEndTime = new EventDateTime().setDateTime(new DateTime(endTime.dateTime)).setTimeZone(endTime.timeZone);
You forget to render it

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +                EventAttendee eventAttendee = new EventAttendee().setDisplayName(attendee.displayName).setEmail(attendee.email);
You forget to render it

2024-11-05 13:32 UTC, loicmathieu commented on src/main/java/io/kestra/plugin/googleworkspace/calendar/AbstractInsertEvent.java
> +            Creator eventCreator = new Event.Creator().setDisplayName(creator.displayName).setEmail(creator.email);
You forget to render it

2024-11-05 19:47 UTC, shrutimantri commented
Addressed the comments

2024-11-06 08:52 UTC, loicmathieu approved these changes
LGTM

2024-11-06 08:52 UTC, merged